### PR TITLE
add `ReadQueryEntity` used to read query parameters into a specified struct

### PR DESCRIPTION
**Pull request by lexkong**
add ReadQueryEntity used to read query parameters into a specified struct

### CODE REVIEW

**Comment by tianxiaoliang** [comment]
Can one of the admins verify this patch?

**Comment by tianxiaoliang** [comment]
plz also give a simple example here, https://github.com/go-chassis/go-chassis-examples
all example is named as a scenario name

**Comment by lexkong** [comment]
> Can one of the admins verify this patch?



> plz also give a simple example here, https://github.com/go-chassis/go-chassis-examples
> all examples are named as scenario names

this is a small feature, i don't think it need a example at this repository. but i can document the usage as a function description

**Comment by tianxiaoliang** [comment]
ok

**Comment by lexkong** [comment]
I amend this commit and add more description for this function:
// ReadQueryEntity is used to read query parameters into a specified struct.
// The struct tag should be `form` like:
// type QueryRequest struct {
//     Name string `form:"name"`
//     Password string `form:"password"`
// }

**Comment by tianxiaoliang** [comment]
thanks

**Comment by lexkong** [comment]
> thanks, and add UT plz

done

**Pull request merged**
